import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import { ClienteAuthProvider } from "./components/ClienteAuthProvider";
import { VisitTracker } from "./components/VisitTracker";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${lora.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClienteAuthProvider>
          <VisitTracker />
          {children}
        </ClienteAuthProvider>
      </body>
    </html>
  );
}
