-- Catalogo relacional de produtos.
-- Mantem as colunas textuais existentes como snapshots para compatibilidade
-- com pedidos, WhatsApp e futuras integracoes ERP.

begin;

-- Categorias ja existem no banco atual e deixam de depender obrigatoriamente
-- de um departamento. Nenhuma categoria ou departamento e removido.
alter table public.categorias
  alter column departamento_id drop not null;

alter table public.categorias
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists categorias_nome_unique
  on public.categorias (lower(nome));

-- Evita ON CONFLICT com indice por expressao. Este bloco tambem funciona caso
-- a migration seja retomada depois de uma execucao interrompida.
insert into public.categorias (nome, ativo, ordem)
select seed.nome, true, seed.ordem
from (
  values
    ('Camisas', 10), ('Camisetas', 20), ('Calças', 30), ('Botas', 40),
    ('Botinas', 50), ('Chapéus', 60), ('Bonés', 70), ('Cintos', 80),
    ('Bolsas', 90), ('Vestidos', 100), ('Saias', 110),
    ('Acessórios', 120), ('Outros', 130)
) as seed(nome, ordem)
where not exists (
  select 1
  from public.categorias c
  where lower(c.nome) = lower(seed.nome)
);

create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nome text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists marcas_nome_unique
  on public.marcas (lower(nome));

insert into public.marcas (nome, ativo)
select 'Indefinida', true
where not exists (
  select 1 from public.marcas where lower(nome) = 'indefinida'
);

-- Se a linha ja existia, garante que a marca padrao esteja utilizavel.
update public.marcas
set nome = 'Indefinida', ativo = true
where lower(nome) = 'indefinida'
  and (nome is distinct from 'Indefinida' or ativo is distinct from true);

alter table public.produtos
  add column if not exists marca_id bigint references public.marcas(id) on delete restrict;

update public.produtos
set marca_id = (
  select id from public.marcas where lower(nome) = 'indefinida' limit 1
)
where marca_id is null;

-- Publico passa a ser obrigatorio sem descartar produtos preexistentes.
update public.produtos
set publico = 'Unissex'
where publico is null or btrim(publico) = '';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.produtos'::regclass
      and conname = 'produtos_publico_check'
  ) then
    alter table public.produtos
      add constraint produtos_publico_check
      check (publico in ('Masculino', 'Feminino', 'Infantil', 'Unissex'));
  end if;
end;
$$;

alter table public.produtos
  alter column publico set not null,
  alter column marca_id set not null;

create index if not exists produtos_marca_id_idx
  on public.produtos (marca_id);

create or replace function public.set_default_product_brand()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.marca_id is null then
    select id into new.marca_id
    from public.marcas
    where lower(nome) = 'indefinida' and ativo = true
    limit 1;
  end if;

  if new.marca_id is null then
    raise exception 'A marca padrao Indefinida nao foi encontrada.';
  end if;

  return new;
end;
$$;

drop trigger if exists produtos_set_default_brand on public.produtos;
create trigger produtos_set_default_brand
before insert or update of marca_id on public.produtos
for each row execute function public.set_default_product_brand();

-- Impede que operacoes acidentais removam a marca exigida pelo cadastro.
create or replace function public.protect_default_brand()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if lower(old.nome) = 'indefinida' then
    if tg_op = 'DELETE' then
      raise exception 'A marca padrao Indefinida nao pode ser excluida.';
    end if;

    if lower(new.nome) <> 'indefinida' or new.ativo is not true then
      raise exception 'A marca padrao Indefinida nao pode ser renomeada ou inativada.';
    end if;
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists marcas_protect_default on public.marcas;
create trigger marcas_protect_default
before update or delete on public.marcas
for each row execute function public.protect_default_brand();

-- produtos.id e integer no schema atual; usar o mesmo tipo evita uma FK
-- implicitamente divergente das tabelas de vendas e estoque.
create table if not exists public.produto_imagens (
  id bigint generated by default as identity primary key,
  produto_id integer not null references public.produtos(id) on delete cascade,
  tipo_midia text not null default 'imagem',
  url text not null,
  storage_path text,
  ordem smallint not null default 0,
  principal boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint produto_imagens_tipo_check check (tipo_midia in ('imagem', 'video')),
  constraint produto_imagens_ordem_check check (ordem between 0 and 9),
  constraint produto_imagens_produto_ordem_key unique (produto_id, ordem)
);

create unique index if not exists produto_imagens_principal_unique
  on public.produto_imagens (produto_id)
  where principal;

create index if not exists produto_imagens_produto_ordem_idx
  on public.produto_imagens (produto_id, ordem);

-- Uma imagem por posicao (0..9) limita estruturalmente a galeria a 10 itens.
insert into public.produto_imagens (
  produto_id, tipo_midia, url, storage_path, ordem, principal
)
select p.id, 'imagem', p.imagem_principal, null, 0, true
from public.produtos p
where p.imagem_principal is not null
  and not exists (
    select 1 from public.produto_imagens pi where pi.produto_id = p.id
  );

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists categorias_set_updated_at on public.categorias;
create trigger categorias_set_updated_at
before update on public.categorias
for each row execute function public.set_updated_at();

drop trigger if exists marcas_set_updated_at on public.marcas;
create trigger marcas_set_updated_at
before update on public.marcas
for each row execute function public.set_updated_at();

drop trigger if exists produto_imagens_set_updated_at on public.produto_imagens;
create trigger produto_imagens_set_updated_at
before update on public.produto_imagens
for each row execute function public.set_updated_at();

-- Substitui a galeria em uma unica transacao no servidor. A funcao nao faz
-- upload: ela apenas sincroniza metadados ja validados pela rota administrativa.
create or replace function public.sincronizar_produto_imagens(
  p_produto_id integer,
  p_imagens jsonb
)
returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_count integer;
begin
  if jsonb_typeof(p_imagens) is distinct from 'array' then
    raise exception 'Galeria invalida.';
  end if;

  v_count := jsonb_array_length(p_imagens);
  if v_count < 1 or v_count > 10 then
    raise exception 'A galeria deve conter de 1 a 10 itens.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_imagens) item
    where coalesce(item->>'tipo_midia', 'imagem') not in ('imagem', 'video')
      or nullif(btrim(item->>'url'), '') is null
  ) then
    raise exception 'Item de galeria invalido.';
  end if;

  delete from public.produto_imagens
  where produto_id = p_produto_id;

  insert into public.produto_imagens (
    produto_id, tipo_midia, url, storage_path, ordem, principal
  )
  select
    p_produto_id,
    coalesce(item->>'tipo_midia', 'imagem'),
    item->>'url',
    nullif(item->>'storage_path', ''),
    (ordinality - 1)::smallint,
    ordinality = 1
  from jsonb_array_elements(p_imagens) with ordinality as gallery(item, ordinality);
end;
$$;

revoke all on function public.sincronizar_produto_imagens(integer, jsonb) from public;
revoke all on function public.sincronizar_produto_imagens(integer, jsonb) from anon;
revoke all on function public.sincronizar_produto_imagens(integer, jsonb) from authenticated;
grant execute on function public.sincronizar_produto_imagens(integer, jsonb) to service_role;

-- Predicado minimo para a policy publica de imagens. SECURITY DEFINER evita
-- que o resultado dependa das policies preexistentes de produtos, sem expor
-- qualquer dado do produto.
create or replace function public.produto_esta_ativo(p_produto_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.produtos p
    where p.id = p_produto_id and p.ativo = true
  );
$$;

revoke all on function public.produto_esta_ativo(integer) from public;
grant execute on function public.produto_esta_ativo(integer) to anon, authenticated, service_role;

-- RLS: anon/authenticated so leem registros ativos necessarios a vitrine.
-- Nenhuma policy de escrita e criada; rotas administrativas usam service_role,
-- que contorna RLS no servidor depois da autenticacao administrativa.
alter table public.categorias enable row level security;
alter table public.marcas enable row level security;
alter table public.produto_imagens enable row level security;

revoke insert, update, delete, truncate, references, trigger
  on table public.categorias from anon, authenticated;
revoke insert, update, delete, truncate, references, trigger
  on table public.marcas from anon, authenticated;
revoke insert, update, delete, truncate, references, trigger
  on table public.produto_imagens from anon, authenticated;

grant select on table public.categorias to anon, authenticated;
grant select on table public.marcas to anon, authenticated;
grant select on table public.produto_imagens to anon, authenticated;

drop policy if exists categorias_public_select_active on public.categorias;
create policy categorias_public_select_active
on public.categorias
for select
to anon, authenticated
using (ativo = true);

drop policy if exists marcas_public_select_active on public.marcas;
create policy marcas_public_select_active
on public.marcas
for select
to anon, authenticated
using (ativo = true);

drop policy if exists produto_imagens_public_select_active on public.produto_imagens;
create policy produto_imagens_public_select_active
on public.produto_imagens
for select
to anon, authenticated
using (public.produto_esta_ativo(produto_id));

commit;
